python run_parallel.py \
    --group_name design_study \
    --exp_name l_alpha_init_05 \
    --agent_config hyper_sac_dev \
    --env_type all \
    --device_ids 0 \
    --num_seeds 10 \
    --num_exp_per_device 1 \
    --overrides agent.actor_alpha_init=0.5 \
    --overrides agent.critic_alpha_init=0.5 \
