python run_parallel.py \
    --group_name design_study \
    --exp_name i_no_lr_decay \
    --agent_config hyper_sac_dev \
    --env_type all \
    --device_ids 0 \
    --num_seeds 10 \
    --num_exp_per_device 1 \
    --overrides agent.actor_learning_rate_end=0.0001 \
    --overrides agent.critic_learning_rate_end=0.0001 \
