python run_parallel.py \
    --group_name simba_plus \
    --exp_name simba_plus \
    --agent_config sac_simba_plus \
    --env_type all \
    --device_ids 0 1 2 3 \
    --num_seeds 10 \
    --num_exp_per_device 8 \
    --server kaist \
    --overrides project_name='Simba_2412' \
    --overrides updates_per_interaction_step=2 \
